### ISSUE TITLE
Can't install plugin on ES 0.20.4

### ISSUE THREAD

**Issue by mdojwa** [bleskes/elasticfacets#5] opened 2013-02-01 21:23 UTC
Hi,

After upgrading ES to 0.20.4 plugin installation does not work:
# plugin -install bleskes/elasticfacets/

-> Installing bleskes/elasticfacets/...
Trying https://github.com/bleskes/elasticfacets/zipball/master... (assuming site plugin)
Downloading ............DONE
Plugin installation assumed to be site plugin, but contains source code, aborting installation...
# plugin -install bleskes/elasticfacets/0.2

-> Installing bleskes/elasticfacets/0.2...
Trying http://download.elasticsearch.org/bleskes/elasticfacets/elasticfacets-0.2.zip...
Trying http://search.maven.org/remotecontent?filepath=bleskes/elasticfacets/0.2/elasticfacets-0.2.zip...
Trying https://oss.sonatype.org/service/local/repositories/releases/content/bleskes/elasticfacets/0.2/elasticfacets-0.2.zip...
Trying https://github.com/bleskes/elasticfacets/zipball/v0.2... (assuming site plugin)
Downloading ......DONE
Plugin installation assumed to be site plugin, but contains source code, aborting installation...

None of the above methods installs plugin, there is nothing in <ES>/plugin directory.

**Comment by bleskes** [comment] 2013-02-02 17:51
Closing. Duplicate of #4

**Closed as completed by bleskes** 2013-02-02 17:51 UTC
